# omz: installation path
export ZSH="$HOME/.oh-my-zsh"

# omz: configuration
COMPLETION_WAITING_DOTS="%F{white}loading..%f"
CASE_SENSITIVE="true"

# omz: theme (https://github.com/ohmyzsh/ohmyzsh/wiki/Themes)
ZSH_THEME="bira"

# omz: plugins
plugins=(
    git
    zsh-autosuggestions
    F-Sy-H
    zsh-history-substring-search
    dirhistory
)

source $ZSH/oh-my-zsh.sh

# aliases: user

alias sudo='sudo '
alias mp='mousepad'
alias apt='\nala'
alias oapt='\apt'
alias ond='code /opt/stacks/onedrive/files/'
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

### application exports

# opencode
export PATH=/home/aliya/.opencode/bin:$PATH
